name: Deploy to GCS using Terraform
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6


    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/671902319686/locations/global/workloadIdentityPools/githubaction-pool-jojo/providers/githubaction-jojoprovider"
        service_account: "terraformfinal@itsme-1234.iam.gserviceaccount.com"

    
    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve
